config/routes.rb
Rails.application.routes.draw do
	root to: 'tasks#index'

	get 'login', to: 'sessions#new'
	post 'login', to: 'sessions#create'
	delete 'logout', to: 'sessions#destroy'
	
	get 'signup', to: 'users#new'
	post 'signup', to: 'users#create'
	
	resources :users, only: [:index, :create]
	resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
	validates :content, presence: true, length: {maximum: 100}
	validates :status, presence: true, length: {maximum: 10}
	
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	validates :name, presence: true, length: { maximum: 50 }
	validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
	has_secure_password
	
	has_many :tasks
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  private
  
  def require_user_logged_in
  	unless logged_in?
  		redirect_to login_url
  	end
  end
  
  def counts(user)
    @count_tasks = user.tasks.count
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email]
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログイン成功'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログイン失敗'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました'
    redirect_to root_url
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	before_action :require_user_logged_in, except: [:index]
  before_action :correct_user, only: [:show, :edit, :update, :destroy]

	def index
	  if logged_in?
	  	@task = current_user.tasks.build
	    @tasks = current_user.tasks.order('created_at DESC').page(params[:page])
	  end
	end
  
  def show
  end
  
  def new
  	@task = Task.new
  end
  
  def create
  	@task = current_user.tasks.build(task_params)
  	
  	if @task.save
  		flash[:success] = 'TODOさんが正常に作成されました'
  		redirect_to root_url
  	else
  		flash.now[:danger] = 'TODOさんは作成されませんでした'
  		render :new
  	end
  	
  end
  
  def edit
  end
  
  def update
  	if @task.update(task_params)
  		flash[:success] = 'TODOさんは正常に更新されました'
  		redirect_to @task
  	else
  		flash.now[:danger] = 'TODOさんは更新されませんでした'
  		render :edit
  	end
  end
  
  def destroy
  	@task.destroy
  	
  	flash[:success] = 'TODOさんは正常に削除されました'
  	redirect_to root_url
  end
  
	private
	  
	def task_params
		params.require(:task).permit(:content, :status)
	end
	
	def correct_user
		@task = current_user.tasks.find_by(id: params[:id])
		unless @task
			redirect_to root_url
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  
  include SessionsHelper
  
  def index
    @users = User.all.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @tasks = @user.tasks.order('created_at DESC').page(params[:page])
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザ登録完了'
      session[:user_id] = @user.id
      redirect_to root_url
    else
      flash.now[:danger] = 'ユーザ登録失敗'
      render :new
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end
	
	def logged_in?
		!!current_user
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |task_type, task| %>
	<div class="alert alert-<%= task_type %>"><%= task %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">TODOlist</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to  '新規リスト作成', new_task_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li role="separator" class="divider"></li>
                <li><%= link_to 'Logout', logout_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to '新規ユーザ登録', signup_path %></li>
            <li><%= link_to 'Login', login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>TODOlist</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    
    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
	<% if task.errors.any? %>
		<div id="error_explanation">
			<ul>
				<% task.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	
	<div class="row">
		<div class="col-xs-12 col-sm-offset-2 col-sm-8 col-lg-offset-3 col-lg-6">
			<div class="form-group">
 				<%= f.label :content, 'TODOさん' %>
  			<%= f.text_field :content, class: "form-control" %>
  		</div>
  
  		<div class="form-group">
  			<%= f.label :status, '状況' %>
 			 	<%= f.text_field :status, class: "form-control" %>
 			</div>
 		</div>
  </div>

  <%= f.submit '投稿', class: 'btn btn-primary btn-block'%>
<% end %>

app/views/tasks/_tasks.html.erb
<ul class="media-list">
	<% tasks.each do |task| %>
		<li class="media">
			<div class="media-body">
				<div>
					<%= link_to task.user.name, user_path(task.user) %> <span class="text-muted">posted at <%= task.created_at %></span>
				</div>
					<p><%= task.content %> &lt; <%= task.status %></p>
			</div>
		</li>
	<% end %>
	<%= paginate tasks %>
</ul>

app/views/tasks/edit.html.erb
<h1>TODOさん編集ページ</h1>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<% if logged_in? %>
	<p>ログイン完了ユーザ: <%= current_user.name %></p>
<h1>TODOリスト</h1>

<ul>
	<% @tasks.each do |task| %>
		<li><%= link_to task.content, task_path(task) %> &lt; <%= task.status %></li>
	<% end %>
</ul>

<% else %>
	<div class="center jumbotron">
		<div class="text-center">
			<h1>さあ、やることを整理しよう</h1>
			<%= link_to '新規ユーザ登録', signup_path, class: 'btn btn-lg btn-primary' %>
		</div>
	</div>
<% end %>

app/views/tasks/new.html.erb
<h1>TODOリスト作成ページ</h1>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h1>TODOさん詳細ページ</h1>

<p>TODOさん: <%= @task.content %></p>
<p>状況: <%= @task.status %></p>

<%= link_to '一覧に戻る', tasks_path %>
<%= link_to 'このTODOさんを編集する', edit_task_path(@task) %>
<%= link_to 'このTODOさんを削除する', @message, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="media-list">
    <% users.each do |user| %>
      <li class="media">
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@user) do |f| %>
    	
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div> 

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
	<div class="panel-heading">
		<h3 class="panel-title"><%= @user.name %></h3>
	</div>

	<div class="col-xs-8">
	  <ul class="nav nav-tabs nav-justified">
	  	<li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>TODOリスト<span class="badge"><%= @count_taskposts %></span><% end %></li>
 	 </ul>
 	 <%= render 'tasks/tasks', tasks: @tasks %>
	</div>
</div>